//
//  CommonConstantStrings.swift
//  UserApp
//
//  Created by Appinventiv on 05/10/17.
//  Copyright © 2017 Appinventiv. All rights reserved.
//

import Foundation



//Signup

let SIGNUP = "SIGNUP"
let DONE = "DONE"
let C_CANCEL = "C_CANCEL"
let FULL_NAME = "FULL_NAME"
let EMAIL_ADDRESS = "EMAIL_ADDRESS"
let PHONE_NO = "PHONE_NO"
let PASSWORD = "PASSWORD"
let GENDER_OPTIONAl = "GENDER_OPTIONAl"
let D_O_B_OPTIONAL = "D_O_B_OPTIONAL"
let MALE = "MALE"
let FEMALE = "FEMALE"
let PRIVACE_AND_TERMS = "PRIVACE_AND_TERMS"
let PROFILR_SETUP = "PROFILR_SETUP"

let S_CHOSE_IMAGE = "S_CHOSE_IMAGE"
let S_CAMERA = "S_CAMERA"
let S_GALLERA = "S_GALLERA"
let S_CANCEL = "S_CANCEL"
let CAMERA_UNAVAIL = "CAMERA_UNAVAIL"
let GALLERY_UNAVAIL = "GALLERY_UNAVAIL"
let CAMERA_UNAVAIL_DESC = "CAMERA_UNAVAIL_DESC"
let CAMERA_PERMISSION = "CAMERA_PERMISSION"
let GALLERY_PERMISSION = "GALLERY_PERMISSION"
let S_SETTINGS = "S_SETTINGS"
let S_OK = "S_OK"
let C_OK = "C_OK"
let PLEASE_ENTER_NAME = "PLEASE_ENTER_NAME"
let PLEASE_ENTER_EMAIL = "PLEASE_ENTER_EMAIL"

let PLEASE_ENTER_VAILD_EMAIL = "PLEASE_ENTER_VAILD_EMAIL"
let SELECT_CODE = "SELECT_CODE"

let PLEASE_ENTER_MOBILE = "PLEASE_ENTER_MOBILE"
let PLEASE_ENTER_VALID_MO = "PLEASE_ENTER_VALID_MO"
let CAN_NOT_CHANGE_EMAIL = "CAN_NOT_CHANGE_EMAIL"
let ACCEPT_TERMS = "ACCEPT_TERMS"
let ALTEST_ONE_VEHICLE = "ALTEST_ONE_VEHICLE"
let PLEASE_ENTER_PASS = "PLEASE_ENTER_PASS"
let PASS_MINIMUM = "PASS_MINIMUM"
let PASS_MAX = "PASS_MAX"

let FILL_CURRENT_PASS = "FILL_CURRENT_PASS"
let FILL_NEW_PASS = "FILL_NEW_PASS"
let CONFIRM_PASS = "CONFIRM_PASS"
let REMOVED = "REMOVED"


//login with media

let LOGIN_WITH_FB = "LOGIN_WITH_FB"
let LOGIN_WITH_TWTR = "LOGIN_WITH_TWTR"
let LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE"
let LOGIN_WITH_EMAIL = "LOGIN_WITH_EMAIL"
let REGISTER_NOW = "REGISTER_NOW"
let PLZ_ENTER_CREDENTIAL = "PLZ_ENTER_CREDENTIAL"

//login

let LOGIN_FORGOT_PASSWORD = "LOGIN_FORGOT_PASSWORD"
let LOGIN = "LOGIN";

// COUNTRY LIST

let C_COUNTRY_LIST = "C_COUNTRY_LIST"
let S_COUNTRY_LIST = "S_COUNTRY_LIST"

// OTP VIEW CONTROLLER

let DONT_WORRY = "DONT_WORRY"
let OTP_DESC = "OTP_DESC"
let OTP_ENTER_OTP = "OTP_ENTER_OTP"
let C_VARIFY = "C_VARIFY"
let C_RESEND = "C_RESEND"

// FORGOT PASSWORD

let FORGIE_ENTER_MOBILE_NUMBER = "FORGIE_ENTER_MOBILE_NUMBER"
let CODE = "CODE"
let MOBILE_NUMBER = "MOBILE_NUMBER"
let C_SEND = "C_SEND"
let FORGOT_PASSWORD = "FORGOT_PASSWORD"

//UPDATE PASSWORD

let PLEASE_ENTER_NEW_PASS = "PLEASE_ENTER_NEW_PASS"
let PLEASE_ENTER_CONFIRM_PASS = "PLEASE_ENTER_CONFIRM_PASS"
let C_UPDATE = "C_UPDATE"

//MOBILE VARIFICATION

let M__VARIFY_ENTER_MOB = "M__VARIFY_ENTER_MOB"
let C_SUBMIT = "C_SUBMIT"

//OTP VARIFICATION

let MOBILE_VARIFICATION = "MOBILE_VARIFICATION"
let ENTER_VARIFY_CODE = "ENTER_VARIFY_CODE"
let C_RESEND_OTP = "C_RESEND_OTP"
let PLZ_ENTER_OTP = "PLZ_ENTER_OTP"
let PLZ_ENTER_VALID_OTP = "PLZ_ENTER_VALID_OTP"
let PLZ_ENTER_COUPON_CODE = "PLZ_ENTER_COUPON_CODE"
let PLZ_ENTER_QUERY = "PLZ_ENTER_QUERY"



//SecondTutorialViewController

let STAY_SAFE = "STAY_SAFE"
let STAY_SAFE_DESC = "STAY_SAFE_DESC"


//ThirdTutorialViewController

let SIMPLE_STRAIGHT = "SIMPLE_STRAIGHT"
let SIMPLE_STRAIGHT_DESC = "SIMPLE_STRAIGHT_DESC"


//FirstTutorialViewController

let AFFORDABLE = "AFFORDABLE"
let AFFORDABLE_DESC = "AFFORDABLE_DESC"


//SubscriptionCardDetailVC

let C_CARD_DETAILS = "C_CARD_DETAILS"
let S_CARD_DETAIL = "S_CARD_DETAIL"
let ENTER_CARD_DETAIL = "ENTER_CARD_DETAIL"
let S_CARD_NO = "S_CARD_NO"
let EXPIRY_DATE = "EXPIRY_DATE"
let CVV = "CVV";
let C_PAY_NOW = "C_PAY_NOW"
let SELECT_CARD = "SELECT_CARD"
let S_DELETE = "S_DELETE"

//SubscriptionAddAmountVC

let C_ADD_AMOUNT = "C_ADD_AMOUNT"
let AMOUNT_AVAILABLE = "AMOUNT_AVAILABLE"
let S_ENTER_AMOUNT = "S_ENTER_AMOUNT"
let C_ENTER_AMOUNT = "C_ENTER_AMOUNT"
let PLEASE_ENTER_AMNT = "PLEASE_ENTER_AMNT"

let LESS_AMOUNT = "LESS_AMOUNT"
let ENTER_CARD_NO = "ENTER_CARD_NO"
let ENTER_VALID_CARD_NO = "ENTER_VALID_CARD_NO"
let ENTER_CARD_HOLDER_NAME = "ENTER_CARD_HOLDER_NAME"
let ENTER_EXPIRY_MONTH = "ENTER_EXPIRY_MONTH"
let ENTER_EXPIRY_YEAR = "ENTER_EXPIRY_YEAR"

let ENTER_VALID_CVV = "ENTER_VALID_CVV"


//SubscriptionVC

let C_SUBSCRIPTION = "C_SUBSCRIPTION"
let VIEW_COUPONS = "VIEW_COUPONS"
let C_LAST_TRANSACTIONS = "C_LAST_TRANSACTIONS"

//SubScriptionCouponsVC

let C_COUPONS = "C_COUPONS"
let C_AVAILABLE = "C_AVAILABLE"
let C_SHARED = "C_SHARED"
let COUPON_AVAILABLE = "COUPON_AVAILABLE"
let GENERATE_COUPONS = "GENERATE_COUPONS"
let NOTE = "NOTE"
let RATE_THE_DRIVER = "RATE_THE_DRIVER"




//Ride related
let SEARCH_DRIVER_ON_LOCATION = "SEARCH_DRIVER_ON_LOCATION"
let REQUEST_RIDE = "REQUEST_RIDE"
let SELCT_DROP_LOC = "SELCT_DROP_LOC"
let SELECT_DATE_AND_TIME = "SELECT_DATE_AND_TIME"
let CAN_NOT_MORE_LOC = "CAN_NOT_MORE_LOC"
let CHOOSE_YOUR_PICKUP = "CHOOSE_YOUR_PICKUP"
let SELECT_LOC = "SELECT_LOC"
let DROP_DESTI_UPDATED = "DROP_DESTI_UPDATED"
let CHANGE_ROUTE_REJECTED = "CHANGE_ROUTE_REJECTED"
let YOU_WILL_REACH_TO_UR_DESTI = "YOU_WILL_REACH_TO_UR_DESTI"
let YOUR_DRIVER_REACH_IN = "YOUR_DRIVER_REACH_IN"

let CHOOSE_PICKUP = "CHOOSE_PICKUP"
let CHOOSE_DROPoFF = "CHOOSE_DROPoFF"
let DROP_OFF = "DROP_OFF"
let S_CHOOSE_DROPOFF = "S_CHOOSE_DROPOFF"
let PICK_UP = "PICK_UP"
let ARE_U_SURE_CANCEL_RIDE = "ARE_U_SURE_CANCEL_RIDE"
let DRIVER_NOT_ALLOCATED = "DRIVER_NOT_ALLOCATED"
let NO_SAVED_LOC = "NO_SAVED_LOC"
//VEHICLE

let MY_VEHICLES = "MY_VEHICLES"
let ADD_NEW_VEHICLES = "ADD_NEW_VEHICLES"

let ENTER_VEHI_MODEL = "ENTER_VEHI_MODEL"
let SELECTVEHI_TYPE = "SELECTVEHI_TYPE"
let ENTER_VEHI_NUMBER = "ENTER_VEHI_NUMBER"
let VEHI_ADDED = "VEHI_ADDED"

let C_CANCELLED = "C_CANCELLED"
let C_COMPLETED = "C_COMPLETED"
let C_ONRIDE = "C_ONRIDE"
let C_ARRIVAL_NOW = "C_ARRIVAL_NOW"

let CARD = "CARD"
let CASH = "CASH"
let CAR = "CAR"
let BIKE = "BIKE"

let C_ARRIVING_NOW = "C_ARRIVING_NOW"
let C_ON_RIDE = "C_ON_RIDE"
let C_ON_THE_WAY = "C_ON_THE_WAY"
let C_CHANGE_DESTI = "C_CHANGE_DESTI"

let S_ONRIDE = "S_ONRIDE"
let S_ARRIVAL_NOW = "S_ARRIVAL_NOW"
let S_RATING = "S_RATING"

let RIDE_CANCELLED = "RIDE_CANCELLED"

let TERRIBLE = "TERRIBLE"
let BAD = "BAD"
let GOOD = "GOOD"
let EXCELLENT = "EXCELLENT"

let CLEANLINESS = "CLEANLINESS"
let S_PICKUP = "S_PICKUP"
let SERVICE = "SERVICE"
let NAVIGATION = "NAVIGATION"
let DRIVING = "DRIVING"
let OTHER = "OTHER"

let WHAT_WENT_WRONG = "WHAT_WENT_WRONG"
let WHAT_COULD_BE_BETTER = "WHAT_COULD_BE_BETTER"
let WHAT_WENT_WELL = "WHAT_WENT_WELL"

// No data found

let NO_HISTORY = "NO_HISTORY"
let NO_NOTIFICATION = "NO_NOTIFICATION"
let NO_PROMOTION = "NO_PROMOTION"
let NO_PREBOOKING = "NO_PREBOOKING"
let NO_TRANSACTION = "NO_TRANSACTION"
let NO_AVAILABLE_COUPON = "NO_AVAILABLE_COUPON"
let NO_SHARED_COUPON = "NO_SHARED_COUPON"

